#!/bin/sh
export PATH=/usr/local/mcuxpressoide-11.5.0_7232/ide/plugins/com.nxp.mcuxpresso.tools.bin.linux_11.5.0.202112161149/binaries/:/usr/local/mcuxpressoide-11.5.0_7232/ide/plugins/com.nxp.mcuxpresso.tools.linux_11.5.0.202107051138/tools/bin:$PATH

cd Release/

make -r -j all

arm-none-eabi-objcopy -O binary MKL26Z4_Project_jlink-test2.axf output.bin

echo "yay!"
